### ISSUE TITLE
Make bootstrapper available as a compiled CLI

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-community/bootstrapper#49]
In #34 @ryanmoran brought up the idea of creating releases of the bootstrapper so that we can make it available as a compiled CLI. This could make the bootstrapper easier to use.

Opening this issue so this suggestion doesn't get forgotten now that #34 is closed.

**Comment by genevieve** [comment]
I support this!

**Comment by ForestEckhardt** [comment]
We should maybe hold off on this and build out an alternative template for `pack`. There is an open RFC to add functionality for alternative templates https://github.com/buildpacks/rfcs/pull/212.

**Comment by sophiewigmore** [comment]
@ForestEckhardt Thanks for pointing out this RFC, I could see that being a worthwhile thing to look into. That being said, I can also imagine a scenario in which there might be friction towards having a packit template in pack, since packit is tightly associated with Paketo, whereas libcnb is a CNB-supported API binding. 
I think it would still be worth it to have the Paketo-powered bootstrapper available, regardless.
