### ISSUE TITLE
Update bootstrapper to receive github-config and dependency updates

### ISSUE THREAD

**Issue by fg-j** [paketo-community/bootstrapper#52]
The bootstrapper has fallen out of date in a number of ways including
- the version of packit, occam, etc. in the template `go.mod`
- the workflows in the template `.github` directory

These should be resolved so buildpack authors have a seamless and up-to-date bootstrapping experience. First-time contributors likely won't have enough context to un-tangle the issues they run into caused by out-of-date setup.

**Comment by sophiewigmore** [comment]
@fg-j I'm not sure that there's a way to keep the workflows up to date in the `template-cnb` directory, it doesn't look like GHA has a way to use workflows that aren't in a top level `.github`. If I understand this issue properly, the main issue was the `go.mod` being out of date?

**Comment by fg-j** [comment]
I think the workflows and scripts being out of date was also an issue. If the repo could somehow use the github config sync action but update the files that live in `template-cnb/.github/workflows` instead of the `.github` directory, that'd be helpful. Seems like [the sync action](https://github.com/paketo-buildpacks/github-config/blob/main/actions/sync/action.yml) takes an arg that specifies into where to sync the desired files, so I think it'd be do-able to have `template-cnb/.github/workflows` and `template-cnb/scripts` consistently look like an up-to-date implementation buildpack.

**Comment by ryanmoran** [comment]
Yes. The `workspace` argument can point at an arbitrary path so it can be pointed at a sub-directory within the repo.

**Comment by sophiewigmore** [comment]
PRs such as https://github.com/paketo-community/bootstrapper/pull/59 and https://github.com/paketo-community/bootstrapper/pull/60 are now getting opened to bump versions in the `go.mod`.
It appears that the `update-github-config` GHA workflow is also scanning the workflows inside `/template-cnb`.
I believe this issue can be closed out now!
